events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    # resolver 127.0.0.11 valid=5s;

	# Rediriger HTTP → HTTPS
	server {
		listen 80;
		return 301 https://$host$request_uri;
	}

    server {
        listen 443 ssl;
        server_name _;

		# Cert de Nginx (présenté au navigateur)
		ssl_certificate     /run/secrets/nginx_crt;
		ssl_certificate_key /run/secrets/nginx_key;

		# CA pour vérifier le cert du BFF (si tu veux mTLS ici aussi)
		# ssl_client_certificate /etc/nginx/certs/ca.crt;
		# ssl_verify_client on;

		ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

		location /api/avatars/ {
			
			proxy_pass https://minio:9000/app-uploads/;

			proxy_set_header Host $http_host;
    		proxy_set_header X-Real-IP $remote_addr;
    		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_set_header X-Forwarded-Proto $scheme;

			# Disable buffering for large asset performance
    		proxy_buffering off;
    		proxy_request_buffering off;

			proxy_ssl_trusted_certificate   /run/secrets/ca_crt;
    		proxy_ssl_verify                on;
		}
		
		location /api/ {
			# set $upstream_bff https://bff:3042/;
            # proxy_pass $upstream_bff;

			proxy_pass https://bff:3042/;
			
			proxy_ssl_certificate           /run/secrets/nginx_crt;
			proxy_ssl_certificate_key       /run/secrets/nginx_key;
			proxy_ssl_trusted_certificate   /run/secrets/ca_crt;
			proxy_ssl_verify                on;
    	}

		# Proxy WebSocket → BFF
		location /socket.io/ {
            # set $upstream_sockets https://bff:3042/socket.io/;
            # proxy_pass $upstream_sockets;
			proxy_pass https://bff:3042/socket.io/;
			proxy_http_version 1.1;
			proxy_set_header Upgrade $http_upgrade;
			proxy_set_header Connection "upgrade";
			proxy_ssl_certificate     /run/secrets/nginx_crt;
			proxy_ssl_certificate_key /run/secrets/nginx_key;
			proxy_ssl_trusted_certificate /run/secrets/ca_crt;
			proxy_ssl_verify on;
		}




        # location ^~ /socket.io/ {
        #     proxy_pass http://service-game:8000;
        #
        #     proxy_http_version 1.1;
        #     proxy_set_header Upgrade $http_upgrade;
        #     proxy_set_header Connection "upgrade";
        #
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_read_timeout 3600s;
        #     proxy_send_timeout 3600s;
        #     proxy_connect_timeout 10s;
        #
        #     proxy_buffering off;
        # }
    }
}